#!/bin/bash

set -x

ls *c *.h|xargs indent -linux

ls *.c|xargs gcc -Wall -g -std=gnu99 -o mywget


url_list=(
    "http://static.mengkang.net/view/images/zs.jpg"
)


for url in ${url_list[@]};do
    ./mywget ${url}
done